export type TCompanyData = {
  ucin: string;
  din: string;
  cin_LLPIN: string;
  nameOfTheCompany: string;
  emailAddress: string;
  role: string;
  roleEffectiveDate: string;
  cessationDate: string;
  directorFlag: string;
  designation: string;
  accountType: string;
  dinAllocationDate: string;
  bodyCorporateType: string;
  profitSharingPercentage: string;
  drivingLicenseNumber: string;
  occupationType: string;
  citizenOfIndia: string;
  bodyCorpOutsideIndiaIDNum: string;
  authorizationStatus: string;
  companyStatus: string;
  bodyCorpInsideIndiaIDNum: string;
  recordCreatedDate: string;
  userName: string;
  companyType: string;
  userId: string;
  dinSurrenderDate: string;
  roleLICValue: string;
  bodyCorpOutsideIndiaId: string;
  middleName: string;
  firstName: string;
  bodyCorpOutsideIndiaName: string;
  companyClass: string;
  residentOfIndia: string;
  fathersLastName: string;
  opcType: string;
  monetaryContributionValue: string;
  companyOrigin: string;
  v2UserId: string;
  pan: string;
  fathersMiddleName: string;
  migrationFlag: string;
  passportNumber: string;
  approverId: string;
  personType: string;
  flagged: string;
  mobileNumber: string;
  fllpDesignation: string;
  companyId: string;
  fathersFirstName: string;
  directorCategory: string;
  nationality: string;
  directorDeathDate: string;
  oldFlag: string;
  srn: string;
  dob: string;
  membershipNumber: string;
  contributionForm: string;
  sboFlag: string;
  bodyCorpInsideIndiaId: string;
  migrationDate: string;
  educationalQualification: string;
  otherOccupation: string;
  compAccountType: string;
  bodyCorpInsideIndiaName: string;
  occupation: string;
  signatoryAssociationStatus: string;
  gender: string;
  isDisqualified: string;
  obligationContribution: string;
  recordUpdatedDate: string;
  shareholdingPercentage: string;
  birthPlace: string;
  opcFlag: string;
  othersEducationalQualification: string;
  lastName: string;
  currentDesignationDate: string;
};

export type TCompanySignatory = {
  din: string;
  cin: string;
  firstName: string;
  middleName: string;
  lastName: string;
  appointmentDate: string;
  dinSurrenderDate: string;
  companyName: string;
  pan: string;
  cessationDate: string;
  accountId: string;
  accountType: string;
  isDisqualified: string;
  designation: string;
  virtueofSharesFlag: string;
  virtueofDistributableDividendFlag: string;
  directorId: string;
  virtueofVotingRightsShares: string;
  personType: string;
  virtueofVotingRightsSharesFlag: string;
  virtueofDistributableDividend: string;
  companyOrigin: string;
  membershipNumber: string;
  virtueofShares: string;
  declarationDate: string;
  directSBOHolding: string;
  flagged: string;
  virtueofExerciseControlFlag: string;
  passportNumber: string;
  declarationReceiptDate: string;
  virtueofSignificantInfluenceFlag: string;
};

export type TMcaSignatoryCessationMasterHistory = {
  cessationDate: string;
  designation: string;
  appointmentDate: string;
  din: string;
  accountName: string;
  cin: string;
};

export type TDirectorAddress = {
  addressType: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  district: string;
  state: string;
  pincode: number;
  country: string;
};
export type TDirector = {
  // _id: {
  //   $oid: string;
  // };
  DIR3KYCFiledFY: string;
  DIR3KYCFiledFlag: string;
  aadhaarNumber: string;
  accountId: string;
  areaOfOccupation: string;
  authorizedRepType: string;
  birthPlace: string;
  citizenOfIndia: string;
  companyData: TCompanyData[];
  companySignatory: TCompanySignatory[];
  createdAt: Date; // FILESURE DATABASE
  createdOn: string; //MCA DATABASE
  din: string;
  dinAllocationDate: string;
  dinSurrenderDate: string;
  directorDeathDate: string;
  directorDisqualified: string;
  directorFlag: string;
  disqualificationDate: string;
  disqualificationReason: string;
  disqualificationRemovalDate: string;
  disqualificationSection: string;
  dob: string;
  drivingLicenseNumber: string;
  durationofStay: string;
  educationalQualification: string;
  emailAddress: string;
  fathersFirstName: string;
  fathersLastName: string;
  fathersMiddleName: string;
  firstName: string;
  gender: string;
  kmpFlag: string;
  lastName: string;
  mcaSignatoryCessationMasterHistory: TMcaSignatoryCessationMasterHistory[];
  membershipNumber: string;
  middleName: string;
  migrationDate: string;
  migrationFlag: string;
  mobileNumber: string;
  nationality: string;
  occupation: string;
  occupationType: string;
  oidFlag: string;
  opcFlag: string;
  opcType: string;
  otherOccupation: string;
  othersEducationalQualification: string;
  pan: string;
  passportNumber: string;
  personType: string;
  personalContact: string;
  residentOfIndia: string;
  sameAddressFlag: string;
  status: string;
  surrenderDeactivationReason: string;
  updatedAt: Date; // FILESURE DATABASE;
  updatedOn: string; // MCA DATABASE
  verificationStatus: string;
  votersIdNumber: string;
  whetherKYCBatchProcessed: string;
  fullName: string;
  addresses: TDirectorAddress[];
  contactUpdated: Date;
  hideContactInfo?: boolean;
};

export interface IOldDirectorData {
  ID: string;
  mobileNumber: string;
  emailAddress: string;
}
